<header class="app-topbar" id="appTopbar" data-turbo-permanent>
    <button class="icon-button" id="sidebarToggle" aria-label="Buka atau tutup navigasi"><i data-lucide="menu"></i></button>
    <div class="d-flex align-items-center gap-2">
        <a href="{{ route('asset-scanner.index') }}" class="icon-button topbar-scan-link" aria-label="Scan QR aset" title="Scan QR aset"><i data-lucide="scan-line"></i><span>Scan QR</span></a>
        <div class="dropdown notification-dropdown"><button class="icon-button position-relative" aria-label="Buka notifikasi" title="Notifikasi" data-bs-toggle="dropdown" aria-expanded="false"><i data-lucide="bell"></i>@if($topbarUnreadCount)<span class="notification-count">{{ $topbarUnreadCount>99?'99+':$topbarUnreadCount }}</span>@endif</button><div class="dropdown-menu dropdown-menu-end notification-menu"><header><strong>Notifikasi</strong>@if($topbarUnreadCount)<form method="POST" action="{{ route('notifications.read-all') }}">@csrf @method('PATCH')<button>Tandai semua dibaca</button></form>@endif</header><div class="notification-menu-list">@forelse($topbarNotifications as $notification)<a href="{{ route('notifications.open',$notification->id) }}" class="notification-menu-item {{ $notification->read_at?'':'unread' }}"><span class="notification-item-icon"><i data-lucide="{{ $notification->data['icon'] ?? 'info' }}"></i></span><span><b>{{ $notification->data['title'] ?? 'Notifikasi' }}</b><small>{{ $notification->data['message'] ?? '' }}</small><time>{{ $notification->created_at->locale('id')->diffForHumans() }}</time></span>@if(!$notification->read_at)<i class="notification-dot"></i>@endif</a>@empty<div class="notification-menu-empty"><b>Tidak ada notifikasi</b><span>Semua informasi penting akan muncul di sini.</span></div>@endforelse</div><footer><a href="{{ route('notifications.index') }}">Lihat Semua Notifikasi</a></footer></div></div>
        <div class="dropdown">
            <button class="user-menu dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><span class="user-avatar">{{ strtoupper(substr(auth()->user()->name, 0, 2)) }}</span><span class="user-meta"><strong>{{ auth()->user()->name }}</strong><small>{{ auth()->user()->roleLabel() }}</small></span></button>
            <ul class="dropdown-menu dropdown-menu-end shadow-sm border"><li><span class="dropdown-item-text small text-secondary">{{ auth()->user()->username }}</span></li><li><hr class="dropdown-divider"></li><li><a class="dropdown-item small" href="{{ route('profile.edit') }}"><i data-lucide="user" class="me-2" style="width:15px"></i>Profil Saya</a></li>@if(auth()->user()->isAdmin())<li><a class="dropdown-item small" href="{{ route('users.index') }}"><i data-lucide="settings" class="me-2" style="width:15px"></i>Pengaturan Akun</a></li>@endif<li><hr class="dropdown-divider"></li><li><form method="POST" action="{{ route('logout') }}">@csrf<button class="dropdown-item small" type="submit"><i data-lucide="log-out" class="me-2" style="width:15px"></i>Keluar</button></form></li></ul>
        </div>
    </div>
</header>
