document.addEventListener('DOMContentLoaded',()=>{const form=document.getElementById('loanForm');if(!form)return;const search=document.getElementById('loanAssetSearch'),select=document.getElementById('loanAsset'),results=document.getElementById('loanAssetResults'),meta=document.querySelectorAll('#loanAssetMeta b'),quantity=document.getElementById('loanQuantity');select.selectedIndex=-1;const close=()=>results.classList.remove('show');const choose=o=>{select.value=o.value;search.value=o.text.trim();search.setCustomValidity('');meta[0].textContent=o.dataset.location;meta[1].textContent=o.dataset.available+' unit';meta[2].textContent=o.dataset.condition;quantity.max=o.dataset.available;close();};const render=()=>{const n=search.value.toLowerCase();results.innerHTML='';[...select.options].filter(o=>o.text.toLowerCase().includes(n)).slice(0,8).forEach(o=>{const b=document.createElement('button');b.type='button';b.className='loan-asset-option';const p=o.text.split('—');b.innerHTML=`<b>${p[0]}</b><span>${p.slice(1).join('—')}</span><small>${o.dataset.available} unit tersedia</small>`;b.onmousedown=e=>{e.preventDefault();choose(o)};results.appendChild(b)});results.classList.add('show')};search.onfocus=render;search.oninput=()=>{select.selectedIndex=-1;render()};search.onblur=()=>setTimeout(close,120);document.getElementById('reviewLoan').onclick=()=>{if(!select.value)search.setCustomValidity('Pilih aset dari daftar.');if(!form.reportValidity())return;const o=select.options[select.selectedIndex],d=v=>document.getElementById(v).value||'—';document.getElementById('loanConfirm').innerHTML=`<div><dt>Aset</dt><dd>${o.text}</dd></div><div><dt>Peminjam</dt><dd>${d('borrowerName')}</dd></div><div><dt>Jumlah</dt><dd>${d('loanQuantity')} unit</dd></div><div><dt>Tanggal</dt><dd>${d('loanDate')}</dd></div><div><dt>Rencana kembali</dt><dd>${d('expectedDate')}</dd></div>`;bootstrap.Modal.getOrCreateInstance(document.getElementById('loanModal')).hide();bootstrap.Modal.getOrCreateInstance(document.getElementById('confirmLoanModal')).show()};document.getElementById('confirmLoan').onclick=()=>{if(form.dataset.submitting)return;form.dataset.submitting='1';form.submit()};document.querySelectorAll('.return-loan').forEach(b=>b.onclick=()=>{document.getElementById('returnForm').action=b.dataset.url;document.getElementById('returnSummary').textContent=`${b.dataset.asset} · ${b.dataset.borrower} · ${b.dataset.loanDate} → ${b.dataset.expected}`});});
document.addEventListener('DOMContentLoaded',()=>{
    document.querySelectorAll('.loan-table [data-bs-toggle="dropdown"]').forEach(toggle=>{
        bootstrap.Dropdown.getOrCreateInstance(toggle,{
            boundary:'viewport',
            popperConfig:config=>({...config,strategy:'fixed'})
        });
    });
});
