<x-app-layout title="Perawatan & Kerusakan">
@push('scripts')@vite('resources/js/asset-maintenances.js')@endpush
<div class="category-page maintenance-page">
    <nav aria-label="breadcrumb"><ol class="breadcrumb category-breadcrumb"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li><li class="breadcrumb-item">Inventaris</li><li class="breadcrumb-item active">Perawatan & Kerusakan</li></ol></nav>
    <header class="category-page-header"><div><h1>Perawatan & Kerusakan</h1><p>Kelola laporan kerusakan dan riwayat perawatan aset sekolah.</p></div>@if(auth()->user()->isAdmin())<button class="btn category-primary-btn" data-bs-toggle="modal" data-bs-target="#maintenanceModal"><i data-lucide="plus"></i>Tambah Perawatan</button>@endif</header>
    <section class="maintenance-summary"><div><span>Menunggu</span><strong>{{ number_format($waitingCount,0,',','.') }}</strong></div><i></i><div><span>Sedang Diproses</span><strong>{{ number_format($processingCount,0,',','.') }}</strong></div><i></i><div><span>Selesai Bulan Ini</span><strong>{{ number_format($completedThisMonth,0,',','.') }}</strong></div><i></i><div><span>Total Biaya Perawatan</span><strong>Rp {{ number_format($totalCost,0,',','.') }}</strong></div></section>
    <section class="category-panel">
        <form class="asset-toolbar maintenance-toolbar" method="GET"><div class="category-search asset-search"><i data-lucide="search"></i><input name="search" value="{{ request('search') }}" placeholder="Cari kode atau nama aset..."></div><div class="asset-filters"><select name="status"><option value="">Semua Status</option>@foreach(['menunggu'=>'Menunggu','diproses'=>'Sedang Diproses','selesai'=>'Selesai','dibatalkan'=>'Dibatalkan'] as $key=>$label)<option value="{{ $key }}" @selected(request('status')===$key)>{{ $label }}</option>@endforeach</select><select name="condition"><option value="">Semua Kondisi</option>@foreach(['baik'=>'Baik','rusak_ringan'=>'Rusak Ringan','rusak_berat'=>'Rusak Berat'] as $key=>$label)<option value="{{ $key }}" @selected(request('condition')===$key)>{{ $label }}</option>@endforeach</select><input type="date" name="date" value="{{ request('date') }}" title="Tanggal laporan"><select name="location"><option value="">Semua Lokasi</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected((string)request('location')===(string)$location->id)>{{ $location->name }}</option>@endforeach</select></div><div class="asset-filter-actions"><button class="btn category-search-btn">Filter</button></div></form>
        @if($maintenances->isEmpty())<div class="category-empty"><div><i data-lucide="wrench"></i></div><h2>Belum ada data perawatan</h2><p>Laporan kerusakan dan perawatan aset akan tampil di sini.</p></div>@else
        <div class="category-table-wrap"><table class="category-table maintenance-table"><thead><tr><th>Tanggal</th><th>Kode Aset</th><th>Nama Aset</th><th>Keluhan</th><th>Kondisi</th><th>Status</th><th>Biaya</th><th class="text-end">Aksi</th></tr></thead><tbody>@foreach($maintenances as $maintenance)<tr><td>{{ $maintenance->reported_date->locale('id')->translatedFormat('d M Y') }}</td><td><b class="asset-code">{{ $maintenance->asset->asset_code }}</b></td><td><b>{{ $maintenance->asset->name }}</b><small>{{ $maintenance->asset->location->name }}</small></td><td><span class="maintenance-issue" title="{{ $maintenance->issue }}">{{ Str::limit($maintenance->issue,45) }}</span></td><td><span class="asset-badge condition-{{ $maintenance->initial_condition }}">{{ $maintenance->initial_condition_label }}</span></td><td><span class="maintenance-status {{ $maintenance->maintenance_status }}">{{ $maintenance->status_label }}</span></td><td>Rp {{ number_format((float)($maintenance->maintenance_status==='selesai'?$maintenance->actual_cost:$maintenance->estimated_cost),0,',','.') }}</td><td class="text-end"><a href="{{ route('asset-maintenances.show',$maintenance) }}" class="category-action" aria-label="Lihat detail"><i data-lucide="eye"></i></a></td></tr>@endforeach</tbody></table></div>
        <div class="category-pagination">
            <div class="pagination-wrapper">
                <span>Tampilkan:</span>
                <select class="per-page-select" onchange="const url = new URL(window.location.href); url.searchParams.set('per_page', this.value); url.searchParams.set('page', 1); window.location.href = url.toString();">
                    <option value="10" @selected(request('per_page', 10) == 10)>10</option>
                    <option value="20" @selected(request('per_page') == 20)>20</option>
                    <option value="50" @selected(request('per_page') == 50)>50</option>
                    <option value="100" @selected(request('per_page') == 100)>100</option>
                </select>
                <span>Menampilkan {{ $maintenances->firstItem() }}–{{ $maintenances->lastItem() }} dari {{ $maintenances->total() }} perawatan</span>
            </div>
            {{ $maintenances->links() }}
        </div>@endif
    </section>
</div>
@if(auth()->user()->isAdmin())
<div class="modal fade category-modal" id="maintenanceModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered modal-xl"><div class="modal-content"><div class="modal-header"><div><h2>Tambah Perawatan</h2><p>Catat keluhan dan rencana penanganan aset.</p></div><button class="btn-close" data-bs-dismiss="modal"></button></div><form method="POST" action="{{ route('asset-maintenances.store') }}" id="maintenanceForm" data-error-modal="maintenanceModal" data-has-errors="{{ $errors->any() ? '1' : '0' }}">@csrf<div class="modal-body">@if($errors->any())<div class="maintenance-validation" role="alert"><i data-lucide="circle-alert"></i><div><strong>Data belum dapat disimpan.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div></div>@endif<div class="maintenance-form-grid">
    <div class="category-form-group span-2 maintenance-asset-picker"><label for="maintenanceAssetSearch">Aset <span>*</span></label><input id="maintenanceAssetSearch" class="form-control" placeholder="Cari kode atau nama aset..." autocomplete="off"><select id="maintenanceAsset" name="asset_id" hidden>@foreach($assets as $asset)<option value="{{ $asset->id }}" data-location="{{ $asset->location->name }}" data-condition="{{ $asset->condition_label }}" data-condition-key="{{ $asset->condition }}" data-status="{{ $asset->status_label }}">{{ $asset->asset_code }} — {{ $asset->name }}</option>@endforeach</select><div id="maintenanceAssetResults" class="maintenance-asset-results"></div><div class="maintenance-asset-meta" id="maintenanceAssetMeta"><span>Lokasi<b>—</b></span><span>Kondisi saat ini<b>—</b></span><span>Status saat ini<b>—</b></span></div>@error('asset_id')<div class="asset-error">{{ $message }}</div>@enderror</div>
    <div class="category-form-group"><label for="reportedDate">Tanggal Lapor <span>*</span></label><input type="date" id="reportedDate" name="reported_date" value="{{ old('reported_date',date('Y-m-d')) }}" class="form-control" required></div><div class="category-form-group"><label for="initialCondition">Kondisi Awal <span>*</span></label><select id="initialCondition" name="initial_condition" class="form-select" required><option value="">Pilih kondisi</option><option value="baik">Baik</option><option value="rusak_ringan">Rusak Ringan</option><option value="rusak_berat">Rusak Berat</option></select></div>
    <div class="category-form-group span-2"><label for="maintenanceIssue">Keluhan / Kerusakan <span>*</span></label><textarea id="maintenanceIssue" name="issue" rows="3" class="form-control" required>{{ old('issue') }}</textarea></div>
    <div class="category-form-group"><label>Status Awal</label><input value="Menunggu" class="form-control" readonly><input type="hidden" name="maintenance_status" value="menunggu"></div><div class="category-form-group"><label for="serviceLocation">Tempat Servis</label><input id="serviceLocation" name="service_location" value="{{ old('service_location') }}" class="form-control"></div><div class="category-form-group"><label for="technician">Teknisi</label><input id="technician" name="technician" value="{{ old('technician') }}" class="form-control"></div><div class="category-form-group"><label for="estimatedCost">Estimasi Biaya</label><input type="number" id="estimatedCost" name="estimated_cost" value="{{ old('estimated_cost',0) }}" min="0" step="1" class="form-control"></div><div class="category-form-group"><label for="startDate">Tanggal Mulai</label><input type="date" id="startDate" name="start_date" value="{{ old('start_date') }}" class="form-control"></div><div class="category-form-group span-2"><label for="maintenanceNotes">Catatan</label><textarea id="maintenanceNotes" name="notes" rows="2" class="form-control">{{ old('notes') }}</textarea></div>
    </div></div><div class="modal-footer"><button type="button" class="btn category-cancel-btn" data-bs-dismiss="modal">Batal</button><button type="button" class="btn category-primary-btn" id="reviewMaintenance">Lanjutkan</button></div></form></div></div></div>
<div class="modal fade category-modal" id="confirmMaintenanceModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><div><h2>Konfirmasi Perawatan</h2><p>Pastikan laporan perawatan sudah benar.</p></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><dl class="maintenance-confirm" id="maintenanceConfirm"></dl></div><div class="modal-footer"><button class="btn category-cancel-btn" data-bs-dismiss="modal">Batal</button><button class="btn category-primary-btn" id="confirmMaintenance">Simpan Perawatan</button></div></div></div></div>
@endif
</x-app-layout>
