<x-app-layout title="Detail Perawatan">
@push('scripts')
@vite('resources/js/asset-maintenances.js')
<template id="maintenanceTrackTemplate">
    <section class="asset-detail-card maintenance-track-card">
        <div class="asset-detail-title"><i data-lucide="history"></i><div><h2>Track Record Perawatan</h2><p>Urutan aktivitas selama penanganan aset.</p></div></div>
        <div class="maintenance-track">
            <article class="completed"><span><i data-lucide="file-plus-2"></i></span><div><time>{{ $maintenance->created_at->locale('id')->translatedFormat('d F Y, H:i') }}</time><h3>Laporan kerusakan dibuat</h3><p>{{ $maintenance->issue }}</p><small>Dicatat oleh {{ $maintenance->creator?->name ?: 'Pengguna tidak tersedia' }} · Tanggal laporan {{ $maintenance->reported_date->locale('id')->translatedFormat('d F Y') }}</small></div></article>
            @if($maintenance->start_date || $maintenance->started_at)
            <article class="completed"><span><i data-lucide="play"></i></span><div><time>{{ $maintenance->started_at?->locale('id')->translatedFormat('d F Y, H:i') ?: $maintenance->start_date->locale('id')->translatedFormat('d F Y') }}</time><h3>Perawatan mulai diproses</h3><p>{{ $maintenance->service_location ? 'Penanganan di '.$maintenance->service_location : 'Aset mulai ditangani.' }}{{ $maintenance->technician ? ' oleh '.$maintenance->technician : '' }}</p><small>Diproses oleh {{ $maintenance->starter?->name ?: 'Data pengguna tidak tersedia' }}</small></div></article>
            @endif
            @if($maintenance->completed_date)
            <article class="completed success"><span><i data-lucide="circle-check"></i></span><div><time>{{ $maintenance->completed_date->locale('id')->translatedFormat('d F Y') }}</time><h3>Perawatan diselesaikan</h3><p>{{ $maintenance->action_taken ?: 'Tindakan perbaikan tidak dicatat.' }}</p><small>Oleh {{ $maintenance->completer?->name ?: 'Pengguna tidak tersedia' }} · Kondisi akhir {{ $maintenance->final_condition_label }} · Rp {{ number_format((float)$maintenance->actual_cost,0,',','.') }}</small></div></article>
            @elseif($maintenance->cancelled_at)
            <article class="completed cancelled"><span><i data-lucide="x-circle"></i></span><div><time>{{ $maintenance->cancelled_at->locale('id')->translatedFormat('d F Y, H:i') }}</time><h3>Perawatan dibatalkan</h3><p>Laporan ditutup dan status aset dikembalikan menjadi tersedia.</p><small>Dibatalkan oleh {{ $maintenance->canceller?->name ?: 'Pengguna tidak tersedia' }}</small></div></article>
            @else
            <article class="current"><span><i data-lucide="clock-3"></i></span><div><time>Saat ini</time><h3>{{ $maintenance->maintenance_status === 'diproses' ? 'Perawatan sedang berlangsung' : 'Menunggu proses perawatan' }}</h3><p>{{ $maintenance->maintenance_status === 'diproses' ? 'Penyelesaian dan hasil akhir belum dicatat.' : 'Aset menunggu untuk mulai ditangani.' }}</p></div></article>
            @endif
        </div>
    </section>
</template>
@endpush
<div class="category-page maintenance-detail-page">
    <nav aria-label="breadcrumb"><ol class="breadcrumb category-breadcrumb"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route('asset-maintenances.index') }}">Perawatan & Kerusakan</a></li><li class="breadcrumb-item active">Detail</li></ol></nav>
    <header class="category-page-header"><div><h1>Detail Perawatan</h1><p>Informasi laporan kerusakan dan penanganan aset.</p></div><div class="maintenance-actions">@if(auth()->user()->isAdmin() && $maintenance->maintenance_status==='menunggu')<form method="POST" action="{{ route('asset-maintenances.start',$maintenance) }}">@csrf @method('PATCH')<button class="btn category-primary-btn"><i data-lucide="play"></i>Mulai Proses</button></form><button class="btn maintenance-danger-btn" data-bs-toggle="modal" data-bs-target="#cancelMaintenanceModal"><i data-lucide="x-circle"></i>Batalkan</button>@elseif(auth()->user()->isAdmin() && $maintenance->maintenance_status==='diproses')<button class="btn category-primary-btn" data-bs-toggle="modal" data-bs-target="#completeMaintenanceModal"><i data-lucide="circle-check"></i>Selesaikan Perawatan</button>@endif<a href="{{ route('asset-maintenances.index') }}" class="btn category-cancel-btn"><i data-lucide="arrow-left"></i>Kembali</a></div></header>
    <div class="maintenance-detail-layout"><main><section class="asset-detail-card maintenance-hero"><div class="maintenance-hero-icon"><i data-lucide="wrench"></i></div><div><small>ASET DALAM PERAWATAN</small><h2>{{ $maintenance->asset->name }}</h2><a href="{{ route('assets.show',$maintenance->asset) }}">{{ $maintenance->asset->asset_code }}</a><p>{{ $maintenance->asset->location->name }}</p></div><span class="maintenance-status {{ $maintenance->maintenance_status }}">{{ $maintenance->status_label }}</span></section>
    <section class="asset-detail-card"><div class="asset-detail-title"><i data-lucide="clipboard-list"></i><div><h2>Informasi Perawatan</h2><p>Rincian laporan dan proses penanganan.</p></div></div><dl class="maintenance-info-grid"><div><dt>Tanggal laporan</dt><dd>{{ $maintenance->reported_date->locale('id')->translatedFormat('d F Y') }}</dd></div><div><dt>Kondisi awal</dt><dd>{{ $maintenance->initial_condition_label }}</dd></div><div class="span-2"><dt>Keluhan / Kerusakan</dt><dd>{{ $maintenance->issue }}</dd></div><div><dt>Tempat servis</dt><dd>{{ $maintenance->service_location ?: '—' }}</dd></div><div><dt>Teknisi</dt><dd>{{ $maintenance->technician ?: '—' }}</dd></div><div><dt>Estimasi biaya</dt><dd>Rp {{ number_format((float)$maintenance->estimated_cost,0,',','.') }}</dd></div><div><dt>Biaya aktual</dt><dd>Rp {{ number_format((float)$maintenance->actual_cost,0,',','.') }}</dd></div><div><dt>Tanggal mulai</dt><dd>{{ $maintenance->start_date?->locale('id')->translatedFormat('d F Y') ?: '—' }}</dd></div><div><dt>Tanggal selesai</dt><dd>{{ $maintenance->completed_date?->locale('id')->translatedFormat('d F Y') ?: '—' }}</dd></div><div class="span-2"><dt>Tindakan perbaikan</dt><dd>{{ $maintenance->action_taken ?: '—' }}</dd></div><div><dt>Kondisi akhir</dt><dd>{{ $maintenance->final_condition_label }}</dd></div><div class="span-2"><dt>Catatan</dt><dd>{{ $maintenance->notes ?: '—' }}</dd></div></dl></section></main>
    <aside><section class="asset-detail-card maintenance-meta"><h2>Informasi Pencatatan</h2><dl><div><dt>Dibuat oleh</dt><dd>{{ $maintenance->creator?->name ?: 'Pengguna tidak tersedia' }}</dd></div><div><dt>Tanggal dibuat</dt><dd>{{ $maintenance->created_at->locale('id')->translatedFormat('d F Y, H:i') }}</dd></div><div><dt>Diselesaikan oleh</dt><dd>{{ $maintenance->completer?->name ?: '—' }}</dd></div><div><dt>Terakhir diperbarui</dt><dd>{{ $maintenance->updated_at->locale('id')->translatedFormat('d F Y, H:i') }}</dd></div></dl></section></aside></div>
</div>
@if(auth()->user()->isAdmin() && $maintenance->maintenance_status==='diproses')<div class="modal fade category-modal" id="completeMaintenanceModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content"><div class="modal-header"><div><h2>Selesaikan Perawatan</h2><p>Catat hasil akhir penanganan {{ $maintenance->asset->name }}.</p></div><button class="btn-close" data-bs-dismiss="modal"></button></div><form method="POST" action="{{ route('asset-maintenances.complete',$maintenance) }}">@csrf @method('PATCH')<div class="modal-body"><div class="maintenance-form-grid"><div class="category-form-group"><label>Tanggal Selesai <span>*</span></label><input type="date" name="completed_date" value="{{ old('completed_date',date('Y-m-d')) }}" min="{{ ($maintenance->start_date ?: $maintenance->reported_date)->format('Y-m-d') }}" class="form-control" required></div><div class="category-form-group"><label>Kondisi Akhir <span>*</span></label><select name="final_condition" class="form-select" required><option value="">Pilih kondisi</option><option value="baik">Baik</option><option value="rusak_ringan">Rusak Ringan</option><option value="rusak_berat">Rusak Berat</option></select></div><div class="category-form-group span-2"><label>Tindakan Perbaikan <span>*</span></label><textarea name="action_taken" rows="3" class="form-control" required>{{ old('action_taken') }}</textarea></div><div class="category-form-group"><label>Biaya Aktual</label><input type="number" name="actual_cost" value="{{ old('actual_cost',0) }}" min="0" step="1" class="form-control"></div><div class="category-form-group span-2"><label>Catatan</label><textarea name="notes" rows="2" class="form-control">{{ old('notes',$maintenance->notes) }}</textarea></div></div></div><div class="modal-footer"><button type="button" class="btn category-cancel-btn" data-bs-dismiss="modal">Batal</button><button class="btn category-primary-btn">Selesaikan Perawatan</button></div></form></div></div></div>@endif
@if(auth()->user()->isAdmin() && $maintenance->maintenance_status==='menunggu')<div class="modal fade category-modal" id="cancelMaintenanceModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><div><h2>Batalkan Perawatan?</h2><p>Aset akan dikembalikan ke status tersedia.</p></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p class="maintenance-cancel-copy">Laporan perawatan <strong>{{ $maintenance->asset->name }}</strong> akan ditandai dibatalkan. Data laporan tetap tersimpan dalam riwayat aset.</p></div><div class="modal-footer"><button class="btn category-cancel-btn" data-bs-dismiss="modal">Kembali</button><form method="POST" action="{{ route('asset-maintenances.cancel',$maintenance) }}">@csrf @method('PATCH')<button class="btn maintenance-danger-btn">Batalkan Perawatan</button></form></div></div></div></div>@endif
</x-app-layout>
