<x-app-layout title="Identitas Sekolah">
<div class="category-page asset-form-page school-setting-page">
    <nav aria-label="breadcrumb"><ol class="breadcrumb category-breadcrumb"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li><li class="breadcrumb-item">Pengaturan</li><li class="breadcrumb-item active">Identitas Sekolah</li></ol></nav>
    <header class="category-page-header"><div><h1>Identitas Sekolah</h1><p>Kelola identitas sekolah yang digunakan pada sistem dan dokumen inventaris.</p></div></header>
    <form method="POST" action="{{ route('school-settings.update') }}" enctype="multipart/form-data" id="schoolSettingForm">@csrf @method('PUT')
        <section class="asset-form-card"><div class="asset-section-heading"><span>01</span><div><h2>Identitas</h2><p>Informasi utama satuan pendidikan.</p></div></div><div class="asset-form-grid">
            <div class="asset-field span-2"><label for="school_name">Nama Sekolah <b>*</b></label><input id="school_name" name="school_name" value="{{ old('school_name',$setting->school_name) }}" class="form-control @error('school_name') is-invalid @enderror">@error('school_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="asset-field"><label for="npsn">NPSN</label><input id="npsn" name="npsn" value="{{ old('npsn',$setting->npsn) }}" class="form-control @error('npsn') is-invalid @enderror" placeholder="Nomor Pokok Sekolah Nasional">@error('npsn')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="asset-field"><label for="principal_name">Nama Kepala Sekolah</label><input id="principal_name" name="principal_name" value="{{ old('principal_name',$setting->principal_name) }}" class="form-control @error('principal_name') is-invalid @enderror">@error('principal_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        </div></section>
        <section class="asset-form-card"><div class="asset-section-heading"><span>02</span><div><h2>Alamat</h2><p>Alamat lengkap lokasi sekolah.</p></div></div><div class="asset-form-grid">
            <div class="asset-field span-2"><label for="address">Alamat</label><textarea id="address" name="address" rows="3" class="form-control @error('address') is-invalid @enderror">{{ old('address',$setting->address) }}</textarea>@error('address')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="asset-field"><label for="village">Desa / Kelurahan</label><input id="village" name="village" value="{{ old('village',$setting->village) }}" class="form-control"></div><div class="asset-field"><label for="district">Kecamatan</label><input id="district" name="district" value="{{ old('district',$setting->district) }}" class="form-control"></div><div class="asset-field"><label for="city">Kabupaten / Kota</label><input id="city" name="city" value="{{ old('city',$setting->city) }}" class="form-control"></div><div class="asset-field"><label for="province">Provinsi</label><input id="province" name="province" value="{{ old('province',$setting->province) }}" class="form-control"></div><div class="asset-field"><label for="postal_code">Kode Pos</label><input id="postal_code" name="postal_code" value="{{ old('postal_code',$setting->postal_code) }}" class="form-control"></div>
        </div></section>
        <section class="asset-form-card"><div class="asset-section-heading"><span>03</span><div><h2>Kontak</h2><p>Informasi kontak resmi sekolah.</p></div></div><div class="asset-form-grid"><div class="asset-field"><label for="phone">Nomor Telepon</label><input id="phone" name="phone" value="{{ old('phone',$setting->phone) }}" class="form-control"></div><div class="asset-field"><label for="email">Email</label><input type="email" id="email" name="email" value="{{ old('email',$setting->email) }}" class="form-control @error('email') is-invalid @enderror">@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="asset-field span-2"><label for="website">Website</label><input type="url" id="website" name="website" value="{{ old('website',$setting->website) }}" class="form-control @error('website') is-invalid @enderror" placeholder="https://sekolah.sch.id">@error('website')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></section>
        <section class="asset-form-card"><div class="asset-section-heading"><span>04</span><div><h2>Logo Sekolah</h2><p>Logo digunakan pada aplikasi dan label inventaris.</p></div></div><div class="asset-field"><div class="school-logo-upload"><div class="school-logo-preview" id="schoolLogoPreview">@if($setting->logo)<img src="{{ Storage::url($setting->logo) }}" alt="Logo {{ $setting->display_name }}">@else<i data-lucide="school"></i><span>Belum ada logo</span>@endif</div><div><label for="logo" class="btn category-cancel-btn photo-select">Pilih Logo Baru</label><input type="file" id="logo" name="logo" accept="image/png,image/jpeg,image/webp" hidden><p>PNG, JPG, JPEG, atau WEBP. Maksimal 2 MB.<br>Biarkan kosong untuk mempertahankan logo saat ini.</p>@error('logo')<div class="asset-error">{{ $message }}</div>@enderror</div></div></div></section>
        <section class="asset-form-card"><div class="asset-section-heading"><span>05</span><div><h2>Identitas Label Inventaris</h2><p>Atur semua tulisan identitas yang tampil pada label barang.</p></div></div><div class="school-label-setting"><div class="asset-form-grid"><div class="asset-field"><label for="inventory_label_title">Judul Label</label><input id="inventory_label_title" name="inventory_label_title" value="{{ old('inventory_label_title',$setting->inventory_label_title ?: 'BARANG INVENTARIS') }}" class="form-control" maxlength="100"></div><div class="asset-field"><label for="inventory_label_mark">Teks Identitas Kanan</label><input id="inventory_label_mark" name="inventory_label_mark" value="{{ old('inventory_label_mark',$setting->label_mark) }}" class="form-control @error('inventory_label_mark') is-invalid @enderror" maxlength="60" placeholder="Contoh: KOPERASI DESA">@error('inventory_label_mark')<div class="invalid-feedback">{{ $message }}</div>@enderror<small>Tulisan di sebelah ikon pada pojok kanan atas label.</small></div><div class="asset-field span-2"><label for="inventory_label_footer">Footer Label</label><input id="inventory_label_footer" name="inventory_label_footer" value="{{ old('inventory_label_footer',$setting->inventory_label_footer ?: 'JAGA & GUNAKAN DENGAN BAIK') }}" class="form-control" maxlength="150"></div></div><aside class="school-label-mini-preview"><span>Preview Label</span><div><div id="miniLogo">@if($setting->logo)<img src="{{ Storage::url($setting->logo) }}" alt="">@else<i data-lucide="school"></i>@endif</div><strong id="miniSchoolName">{{ old('school_name',$setting->display_name) }}</strong><b id="miniLabelTitle">{{ old('inventory_label_title',$setting->label_title) }}</b><small id="miniLabelMark">{{ old('inventory_label_mark',$setting->label_mark) }}</small></div></aside></div></section>
        <div class="asset-form-actions"><a href="{{ route('dashboard') }}" class="btn category-cancel-btn"><i data-lucide="arrow-left"></i>Batal</a><button class="btn category-primary-btn asset-submit" id="settingSubmit"><span class="asset-submit-default"><i data-lucide="save"></i>Simpan Perubahan</span><span class="asset-submit-loading"><span class="auth-spinner"></span>Memproses...</span></button></div>
    </form>
</div>
@push('scripts')@vite('resources/js/school-settings.js')@endpush
</x-app-layout>
