<?php
namespace Tests\Feature;
use App\Models\Asset;use App\Models\AssetLoan;use App\Models\User;use Illuminate\Foundation\Testing\DatabaseTransactions;use Tests\TestCase;
class AssetLoanTest extends TestCase
{
 use DatabaseTransactions;
 private function admin():User{return User::factory()->create(['role'=>User::ROLE_ADMIN]);}
 private function availableAsset():Asset{return Asset::where('status','tersedia')->where('quantity','>',2)->firstOrFail();}
 private function data(Asset $a,array $o=[]):array{return array_merge(['asset_id'=>$a->id,'borrower_name'=>'Budi Santoso','borrower_role'=>'Guru','borrower_phone'=>'08123456789','quantity'=>2,'loan_date'=>'2026-08-10','expected_return_date'=>'2026-08-12','purpose'=>'Kegiatan belajar','notes'=>'Dijaga dengan baik.'],$o);}
 public function test_available_asset_can_be_partially_and_fully_borrowed():void{$a=$this->availableAsset();$this->actingAs($this->admin())->post(route('asset-loans.store'),$this->data($a))->assertRedirect();$loan=AssetLoan::latest('id')->firstOrFail();$this->assertSame('tersedia',$a->fresh()->status);$this->post(route('asset-loans.store'),$this->data($a,['borrower_name'=>'Siti','quantity'=>$a->quantity-2]))->assertRedirect();$this->assertSame('dipinjam',$a->fresh()->status);$this->assertDatabaseHas('asset_loans',['id'=>$loan->id,'quantity'=>2]);}
 public function test_quantity_and_unavailable_asset_are_rejected():void{$a=$this->availableAsset();$this->actingAs($this->admin())->post(route('asset-loans.store'),$this->data($a,['quantity'=>$a->quantity+1]))->assertSessionHasErrors('quantity');foreach(['perawatan','dihapus']as$status){$blocked=Asset::whereKeyNot($a->id)->firstOrFail();$blocked->update(['status'=>$status]);$this->post(route('asset-loans.store'),$this->data($blocked))->assertSessionHasErrors('asset_id');}}
 public function test_return_updates_condition_status_and_history():void{$a=$this->availableAsset();$this->actingAs($this->admin())->post(route('asset-loans.store'),$this->data($a,['quantity'=>$a->quantity]));$loan=AssetLoan::latest('id')->firstOrFail();$this->patch(route('asset-loans.return',$loan),['returned_at'=>'2026-08-13','return_condition'=>'rusak_ringan','return_notes'=>'Ada goresan.'])->assertRedirect(route('asset-loans.show',$loan));$loan->refresh();$a->refresh();$this->assertNotNull($loan->returned_at);$this->assertSame('dikembalikan',$loan->status);$this->assertSame('tersedia',$a->status);$this->assertSame('rusak_ringan',$a->condition);$this->get(route('assets.show',$a))->assertSee('Peminjaman')->assertSee('Pengembalian')->assertSee('Budi Santoso');}
 public function test_overdue_is_dynamic_and_headmaster_is_read_only():void{$a=$this->availableAsset();$this->actingAs($this->admin())->post(route('asset-loans.store'),$this->data($a,['loan_date'=>today()->subDays(3)->format('Y-m-d'),'expected_return_date'=>today()->subDay()->format('Y-m-d')]));$loan=AssetLoan::latest('id')->firstOrFail();$this->assertSame('terlambat',$loan->display_status);$this->get(route('asset-loans.index',['status'=>'terlambat']))->assertSee('Terlambat');$head=User::factory()->create(['role'=>User::ROLE_KEPALA_SEKOLAH]);$this->actingAs($head)->get(route('asset-loans.index'))->assertOk()->assertDontSee('data-bs-target="#loanModal"',false);$this->post(route('asset-loans.store'),$this->data($a))->assertForbidden();$this->patch(route('asset-loans.return',$loan),['returned_at'=>today(),'return_condition'=>'baik'])->assertForbidden();}
}
