<?php
namespace Tests\Feature;
use App\Models\Asset;use App\Models\AssetDisposal;use App\Models\AssetMaintenance;use App\Models\User;use Illuminate\Foundation\Testing\DatabaseTransactions;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Storage;use Tests\TestCase;
class AssetDisposalTest extends TestCase{
use DatabaseTransactions;
private function admin():User{return User::factory()->create(['role'=>User::ROLE_ADMIN]);}private function principal():User{return User::factory()->create(['role'=>User::ROLE_KEPALA_SEKOLAH]);}private function asset():Asset{return Asset::where('status','tersedia')->firstOrFail();}
private function data(Asset $a,array $o=[]):array{return array_merge(['asset_id'=>$a->id,'disposal_date'=>'2026-08-10','reason'=>'Rusak berat dan tidak layak digunakan','disposal_method'=>'pemusnahan','condition_at_disposal'=>$a->condition,'document_number'=>'BA-001','notes'=>'Disaksikan tim sekolah.'],$o);}
public function test_admin_can_submit_with_document_without_deleting_asset():void{Storage::fake('public');$a=$this->asset();$r=$this->actingAs($this->admin())->post(route('asset-disposals.store'),$this->data($a,['document_file'=>UploadedFile::fake()->create('berita-acara.pdf',100,'application/pdf')]));$d=AssetDisposal::latest('id')->firstOrFail();$r->assertRedirect(route('asset-disposals.show',$d));$this->assertSame('diajukan',$d->status);$this->assertSame('tersedia',$a->fresh()->status);Storage::disk('public')->assertExists($d->document_file);$this->get(route('asset-disposals.document',$d))->assertOk();}
public function test_borrowed_maintenance_deleted_and_duplicate_assets_are_rejected():void{$this->actingAs($this->admin());$a=$this->asset();$a->update(['status'=>'dipinjam']);$this->post(route('asset-disposals.store'),$this->data($a))->assertSessionHasErrors('asset_id');$a=$this->asset();$a->update(['status'=>'perawatan']);AssetMaintenance::create(['asset_id'=>$a->id,'reported_date'=>'2026-08-09','issue'=>'Rusak','initial_condition'=>'rusak_berat','maintenance_status'=>'menunggu','created_by'=>auth()->id()]);$this->post(route('asset-disposals.store'),$this->data($a))->assertSessionHasErrors('asset_id');$a=$this->asset();$a->update(['status'=>'dihapus']);$this->post(route('asset-disposals.store'),$this->data($a))->assertSessionHasErrors('asset_id');$a=$this->asset();$this->post(route('asset-disposals.store'),$this->data($a));$this->post(route('asset-disposals.store'),$this->data($a))->assertSessionHasErrors('asset_id');}
public function test_headmaster_can_approve_and_asset_is_locked_from_operations():void{$a=$this->asset();$admin=$this->admin();$this->actingAs($admin)->post(route('asset-disposals.store'),$this->data($a));$d=AssetDisposal::latest('id')->firstOrFail();$head=$this->principal();$this->actingAs($head)->patch(route('asset-disposals.approve',$d))->assertRedirect(route('asset-disposals.show',$d));$this->assertSame('disetujui',$d->fresh()->status);$this->assertSame($head->id,$d->fresh()->approved_by);$this->assertSame('dihapus',$a->fresh()->status);$this->actingAs($admin)->post(route('asset-loans.store'),['asset_id'=>$a->id,'borrower_name'=>'Budi','quantity'=>1,'loan_date'=>'2026-08-10'])->assertSessionHasErrors('asset_id');$this->post(route('asset-mutations.store'),['asset_id'=>$a->id,'to_location_id'=>Asset::whereKeyNot($a->id)->first()->location_id,'mutation_date'=>'2026-08-10'])->assertSessionHasErrors('asset_id');$this->post(route('asset-maintenances.store'),['asset_id'=>$a->id,'reported_date'=>'2026-08-10','issue'=>'Rusak','initial_condition'=>'rusak_berat'])->assertSessionHasErrors('asset_id');$this->get(route('assets.edit',$a))->assertForbidden();}
public function test_rejection_keeps_asset_active_and_requires_reason():void{$a=$this->asset();$this->actingAs($this->admin())->post(route('asset-disposals.store'),$this->data($a));$d=AssetDisposal::latest('id')->firstOrFail();$this->actingAs($this->principal())->patch(route('asset-disposals.reject',$d),[])->assertSessionHasErrors('rejection_reason');$this->patch(route('asset-disposals.reject',$d),['rejection_reason'=>'Dokumen belum lengkap.'])->assertRedirect();$this->assertSame('ditolak',$d->fresh()->status);$this->assertSame('tersedia',$a->fresh()->status);}
public function test_history_summary_master_counts_and_authorization_are_consistent():void{$a=$this->asset();$activeBefore=(int)Asset::where('status','!=','dihapus')->sum('quantity');$admin=$this->admin();$this->actingAs($admin)->post(route('asset-disposals.store'),$this->data($a));$d=AssetDisposal::latest('id')->firstOrFail();$this->patch(route('asset-disposals.approve',$d));$this->get(route('assets.show',$a))->assertSee('Penghapusan Aset')->assertSee('Pemusnahan')->assertSee('Dihapus');$this->get(route('dashboard'))->assertOk();$this->assertSame($activeBefore-$a->quantity,(int)Asset::where('status','!=','dihapus')->sum('quantity'));$head=$this->principal();$new=$this->asset();$this->actingAs($head)->get(route('asset-disposals.index'))->assertOk()->assertDontSee('Ajukan Penghapusan');$this->post(route('asset-disposals.store'),$this->data($new))->assertForbidden();}
}
