<?php
namespace Tests\Feature;
use App\Models\{AssetLoan,User};use App\Notifications\ImportantAssetNotification;use App\Services\AssetNotificationService;use Illuminate\Foundation\Testing\DatabaseTransactions;use Tests\TestCase;
class NotificationCenterTest extends TestCase
{
 use DatabaseTransactions;
 private function user(string $role=User::ROLE_ADMIN):User{return User::factory()->create(['role'=>$role,'is_active'=>true]);}
 private function notify(User $user,string $key='test'):void{$user->notify(new ImportantAssetNotification(['title'=>'Penting','message'=>'Pesan penting','type'=>'system_info','icon'=>'info','target_url'=>'/','entity_type'=>'system','entity_id'=>1,'key'=>$key]));}
 public function test_badge_list_filters_and_read_actions_work():void{$user=$this->user();$this->notify($user);$this->actingAs($user)->get(route('notifications.index'))->assertOk()->assertSee('Penting')->assertSee('Belum Dibaca');$notification=$user->unreadNotifications()->first();$this->patch(route('notifications.read',$notification->id))->assertSessionHas('success');$this->assertNotNull($notification->fresh()->read_at);$this->get(route('notifications.index',['status'=>'read']))->assertOk()->assertSee('Penting');}
 public function test_open_marks_read_and_ownership_is_enforced():void{$owner=$this->user();$other=$this->user();$this->notify($owner);$notification=$owner->unreadNotifications()->first();$this->actingAs($other)->get(route('notifications.open',$notification->id))->assertNotFound();$this->delete(route('notifications.destroy',$notification->id))->assertNotFound();$this->actingAs($owner)->get(route('notifications.open',$notification->id))->assertRedirect('/');$this->assertNotNull($notification->fresh()->read_at);}
 public function test_open_uses_entity_route_without_duplicating_application_base_path():void{$user=$this->user();$user->notify(new ImportantAssetNotification(['title'=>'Penghapusan','message'=>'Disetujui','type'=>'disposal_approved','icon'=>'trash-2','target_url'=>'/inventaris_barang/public/penghapusan-aset/112','entity_type'=>'disposal','entity_id'=>112,'key'=>'disposal:112']));$notification=$user->unreadNotifications()->first();$this->actingAs($user)->get(route('notifications.open',$notification->id))->assertRedirect(route('asset-disposals.show',112));}
 public function test_overdue_notification_is_role_specific_and_not_duplicated():void{$admin=$this->user();$head=$this->user(User::ROLE_KEPALA_SEKOLAH);$loan=AssetLoan::whereNull('returned_at')->first();if(!$loan)$this->markTestSkipped('Tidak ada peminjaman aktif pada dataset.');$loan->update(['expected_return_date'=>today()->subDay()]);$service=app(AssetNotificationService::class);$service->syncOverdue();$service->syncOverdue();$this->assertSame(1,$admin->notifications()->where('data','like','%loan_overdue:'.$loan->id.'%')->count());$this->assertSame(0,$head->notifications()->where('data','like','%loan_overdue:'.$loan->id.'%')->count());}
 public function test_read_all_and_delete_only_affect_notification_records():void{$user=$this->user();$this->notify($user,'one');$this->notify($user,'two');$this->actingAs($user)->patch(route('notifications.read-all'))->assertSessionHas('success');$this->assertSame(0,$user->unreadNotifications()->count());$id=$user->notifications()->first()->id;$this->delete(route('notifications.destroy',$id))->assertSessionHas('success');$this->assertDatabaseMissing('notifications',['id'=>$id]);}
}
