<?php
namespace Tests\Feature;
use App\Models\{Asset,User};
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Hash;
use Tests\TestCase;
class UserManagementTest extends TestCase
{
 use DatabaseTransactions;
 private function admin():User{return User::factory()->create(['role'=>User::ROLE_ADMIN,'is_active'=>true]);}
 private function data(array $overrides=[]):array{return array_merge(['name'=>'Operator Koperasi','username'=>'operator_baru','email'=>'operator@koperasi.test','role'=>User::ROLE_ADMIN,'password'=>'rahasia123','password_confirmation'=>'rahasia123','is_active'=>1],$overrides);}
 public function test_admin_can_manage_both_roles_and_password_is_hashed():void{$admin=$this->admin();$this->actingAs($admin)->get(route('users.index'))->assertOk()->assertSee('Kelola akun dan hak akses pengguna sistem.');$this->post(route('users.store'),$this->data())->assertSessionHas('success','Pengguna berhasil ditambahkan.');$operator=User::where('username','operator_baru')->firstOrFail();$this->assertTrue(Hash::check('rahasia123',$operator->password));$this->post(route('users.store'),$this->data(['username'=>'kepala_baru','email'=>'kepala@koperasi.test','role'=>User::ROLE_KEPALA_SEKOLAH]))->assertSessionHas('success');$this->assertDatabaseHas('users',['username'=>'kepala_baru','role'=>User::ROLE_KEPALA_SEKOLAH]);}
 public function test_validation_unique_and_password_reset_work():void{$this->actingAs($this->admin());$existing=User::firstOrFail();$this->post(route('users.store'),$this->data(['username'=>$existing->username,'password'=>'pendek','password_confirmation'=>'beda']))->assertSessionHasErrors(['username','password']);$target=User::factory()->create();$this->put(route('users.password',$target),['password'=>'password-baru','password_confirmation'=>'password-baru'])->assertSessionHas('success','Password berhasil diperbarui.');$this->assertTrue(Hash::check('password-baru',$target->fresh()->password));}
 public function test_self_protection_inactive_session_and_role_authorization_are_enforced():void{$admin=$this->admin();$this->actingAs($admin)->patch(route('users.toggle',$admin))->assertSessionHasErrors('account');$this->put(route('users.update',$admin),['name'=>$admin->name,'username'=>$admin->username,'email'=>$admin->email,'role'=>User::ROLE_KEPALA_SEKOLAH,'is_active'=>1])->assertSessionHasErrors('account');$head=User::factory()->create(['role'=>User::ROLE_KEPALA_SEKOLAH]);$this->actingAs($head)->get(route('users.index'))->assertForbidden();$this->post(route('users.store'),$this->data())->assertForbidden();$head->update(['is_active'=>false]);$this->get(route('dashboard'))->assertRedirect(route('login'));}
 public function test_deactivation_preserves_user_and_history_name():void{$admin=$this->admin();$target=User::factory()->create(['name'=>'Petugas Historis']);$asset=Asset::firstOrFail();$asset->update(['created_by'=>$target->id]);$this->actingAs($admin)->patch(route('users.toggle',$target))->assertSessionHas('success','Pengguna berhasil dinonaktifkan.');$this->assertDatabaseHas('users',['id'=>$target->id,'is_active'=>false]);$this->assertSame('Petugas Historis',$asset->fresh()->creator->name);}
 public function test_profile_cannot_change_role_and_can_update_password():void{$head=User::factory()->create(['role'=>User::ROLE_KEPALA_SEKOLAH]);$this->actingAs($head)->get(route('profile.edit'))->assertOk()->assertSee('Profil Saya');$this->put(route('profile.update'),['name'=>'Ketua Baru','email'=>'ketua@koperasi.test','role'=>User::ROLE_ADMIN])->assertSessionHas('success');$this->assertSame(User::ROLE_KEPALA_SEKOLAH,$head->fresh()->role);$this->put(route('profile.password'),['password'=>'profil-baru','password_confirmation'=>'profil-baru'])->assertSessionHas('success');$this->assertTrue(Hash::check('profil-baru',$head->fresh()->password));}
}
