<x-app-layout title="Laporan Aset">
<div class="category-page report-page">
<nav><ol class="breadcrumb category-breadcrumb"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li><li class="breadcrumb-item">Laporan</li><li class="breadcrumb-item active">Laporan Aset</li></ol></nav>
<header class="category-page-header"><div><h1>Laporan Aset</h1><p>Rekap dan cetak data inventaris sekolah berdasarkan kebutuhan.</p></div></header>
<section class="report-filter-card"><div class="report-section-heading"><div><i data-lucide="list-filter"></i></div><span><strong>Filter Laporan</strong><small>Sesuaikan data inventaris yang ingin ditampilkan.</small></span></div>
<form method="GET" action="{{ route('asset-reports.index') }}" class="report-filter-form">
<label><span>Tahun Pengadaan</span><select name="year"><option value="">Semua Tahun</option>@foreach($years as $year)<option value="{{ $year }}" @selected(($filters['year']??null)==$year)>{{ $year }}</option>@endforeach</select></label>
<label><span>Kategori</span><select name="category"><option value="">Semua Kategori</option>@foreach($categories as $item)<option value="{{ $item->id }}" @selected(($filters['category']??null)==$item->id)>{{ $item->name }}</option>@endforeach</select></label>
<label><span>Lokasi / Ruangan</span><select name="location"><option value="">Semua Lokasi</option>@foreach($locations as $item)<option value="{{ $item->id }}" @selected(($filters['location']??null)==$item->id)>{{ $item->name }}</option>@endforeach</select></label>
<label><span>Kondisi</span><select name="condition"><option value="">Semua Kondisi</option><option value="baik" @selected(($filters['condition']??null)==='baik')>Baik</option><option value="rusak_ringan" @selected(($filters['condition']??null)==='rusak_ringan')>Rusak Ringan</option><option value="rusak_berat" @selected(($filters['condition']??null)==='rusak_berat')>Rusak Berat</option></select></label>
<label><span>Status <small class="field-hint">Default: aset aktif</small></span><select name="status"><option value="active" @selected(($filters['status']??'active')==='active')>Aktif (selain dihapus)</option><option value="tersedia" @selected(($filters['status']??null)==='tersedia')>Tersedia</option><option value="dipinjam" @selected(($filters['status']??null)==='dipinjam')>Dipinjam</option><option value="perawatan" @selected(($filters['status']??null)==='perawatan')>Perawatan</option><option value="dihapus" @selected(($filters['status']??null)==='dihapus')>Dihapus</option><option value="all" @selected(($filters['status']??null)==='all')>Semua status</option></select></label>
<label><span>Sumber Dana</span><select name="funding_source"><option value="">Semua Sumber Dana</option>@foreach($fundingSources as $item)<option value="{{ $item->id }}" @selected(($filters['funding_source']??null)==$item->id)>{{ $item->name }}</option>@endforeach</select></label>
<label><span>Dari Tanggal</span><input type="date" name="date_from" value="{{ $filters['date_from']??'' }}"></label><label><span>Sampai Tanggal</span><input type="date" name="date_to" value="{{ $filters['date_to']??'' }}"></label>
<label class="report-search"><span>Pencarian</span><div><i data-lucide="search"></i><input name="search" value="{{ $filters['search']??'' }}" placeholder="Cari kode atau nama aset..."></div></label>
<label><span>Urutkan</span><select name="sort"><option value="code">Kode aset</option><option value="name" @selected(($filters['sort']??null)==='name')>Nama aset</option><option value="year_desc" @selected(($filters['sort']??null)==='year_desc')>Tahun terbaru</option><option value="year_asc" @selected(($filters['sort']??null)==='year_asc')>Tahun terlama</option><option value="value_desc" @selected(($filters['sort']??null)==='value_desc')>Nilai tertinggi</option><option value="value_asc" @selected(($filters['sort']??null)==='value_asc')>Nilai terendah</option></select></label>
<div class="report-filter-actions"><button class="btn category-primary-btn"><i data-lucide="search"></i>Tampilkan Laporan</button><a class="btn category-cancel-btn" href="{{ route('asset-reports.index') }}"><i data-lucide="rotate-ccw"></i>Reset</a></div></form>@if($errors->any())<p class="report-filter-error">{{ $errors->first() }}</p>@endif</section>
<div class="report-block-heading"><div><h2>Ringkasan Laporan</h2><p>Angka berikut mengikuti filter yang sedang diterapkan.</p></div><span><i data-lucide="info"></i>Nilai dihitung dari harga per unit × jumlah</span></div>
<section class="report-summary"><div><span>Total Aset</span><strong>{{ number_format($summary['total_assets'],0,',','.') }}</strong><small>jenis aset</small></div><div><span>Total Unit</span><strong>{{ number_format($summary['total_units'],0,',','.') }}</strong><small>unit barang</small></div><div class="wide"><span>Total Nilai Aset</span><strong>Rp {{ number_format($summary['total_value'],0,',','.') }}</strong><small>nilai inventaris</small></div><div><span>Kondisi Baik</span><strong>{{ number_format($summary['good'],0,',','.') }}</strong><small>unit</small></div><div><span>Rusak Ringan</span><strong>{{ number_format($summary['light_damage'],0,',','.') }}</strong><small>unit</small></div><div><span>Rusak Berat</span><strong>{{ number_format($summary['heavy_damage'],0,',','.') }}</strong><small>unit</small></div><div><span>Sedang Dipinjam</span><strong>{{ number_format($summary['borrowed'],0,',','.') }}</strong><small>unit</small></div>@if(in_array($filters['status']??'active',['all','dihapus']))<div><span>Aset Dihapus</span><strong>{{ number_format($summary['deleted'],0,',','.') }}</strong><small>unit historis</small></div>@endif</section>
<section class="category-panel report-result"><header><div><h2>Data Laporan</h2><p>{{ number_format($assets->total(),0,',','.') }} aset sesuai filter</p></div><div class="report-export-actions">@php($query=request()->except('page'))<a data-turbo="false" target="_blank" class="btn report-button" href="{{ route('asset-reports.print',$query) }}"><i data-lucide="printer"></i>Print</a><a data-turbo="false" class="btn report-button" href="{{ route('asset-reports.pdf',$query) }}"><i data-lucide="file-down"></i>Download PDF</a><a data-turbo="false" class="btn report-excel" href="{{ route('asset-reports.excel',$query) }}"><i data-lucide="sheet"></i>Export Excel</a></div></header>
<div class="category-table-wrap"><table class="category-table report-table"><thead><tr><th>No</th><th>Kode</th><th>Nama Aset</th><th>Kategori</th><th>Lokasi</th><th>Sumber Dana</th><th>Tahun</th><th>Jumlah</th><th>Kondisi</th><th>Status</th><th>Nilai per Unit</th><th>Total Nilai</th></tr></thead><tbody>@forelse($assets as $asset)<tr><td>{{ $assets->firstItem()+$loop->index }}</td><td><b>{{ $asset->asset_code }}</b></td><td><b>{{ $asset->name }}</b></td><td>{{ $asset->category->name }}</td><td>{{ $asset->location->name }}</td><td>{{ $asset->fundingSource?->name??'—' }}</td><td>{{ $asset->acquisition_year }}</td><td>{{ $asset->quantity }}</td><td><span class="asset-badge condition-{{ $asset->condition }}">{{ $asset->condition_label }}</span></td><td><span class="asset-badge status-{{ $asset->status }}">{{ $asset->status_label }}</span></td><td>Rp {{ number_format((float)$asset->acquisition_price,0,',','.') }}</td><td><b>Rp {{ number_format((float)$asset->acquisition_price*$asset->quantity,0,',','.') }}</b></td></tr>@empty<tr><td colspan="12" class="report-empty">Tidak ada data aset yang sesuai dengan filter.</td></tr>@endforelse</tbody><tfoot><tr><td colspan="11">Total Nilai Inventaris</td><td>Rp {{ number_format($summary['total_value'],0,',','.') }}</td></tr></tfoot></table></div>@if($assets->hasPages())<div class="category-pagination"><span>Menampilkan {{ $assets->firstItem() }}–{{ $assets->lastItem() }} dari {{ $assets->total() }} aset</span>{{ $assets->links() }}</div>@endif</section>
</div></x-app-layout>
