<x-app-layout title="Tambah Aset">
<div class="category-page asset-form-page">
    <nav aria-label="breadcrumb"><ol class="breadcrumb category-breadcrumb"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li><li class="breadcrumb-item">Inventaris</li><li class="breadcrumb-item"><a href="{{ route('assets.index') }}">Data Aset</a></li><li class="breadcrumb-item active">Tambah Aset</li></ol></nav>
    <header class="category-page-header asset-form-header"><div><h1>Tambah Aset</h1><p>Tambahkan barang baru ke dalam inventaris sekolah.</p></div><div class="auto-code-note"><i data-lucide="info"></i>Kode aset akan dibuat otomatis</div></header>
    <form method="POST" action="{{ route('assets.store') }}" enctype="multipart/form-data" id="assetForm" data-no-submit-loading>@csrf
        <section class="asset-form-card"><div class="asset-section-heading"><span>01</span><div><h2>Informasi Utama</h2><p>Identitas dan klasifikasi barang inventaris.</p></div></div><div class="asset-form-grid">
            <div class="asset-field span-2"><label for="name">Nama Aset <b>*</b></label><input id="name" name="name" value="{{ old('name') }}" class="form-control @error('name') is-invalid @enderror" placeholder="Contoh: Laptop ASUS X415">@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="asset-field"><label for="category_id">Kategori <b>*</b></label><select id="category_id" name="category_id" class="form-select @error('category_id') is-invalid @enderror"><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id')==$category->id)>{{ $category->name }}</option>@endforeach</select>@error('category_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="asset-field"><label for="brand">Merk</label><input id="brand" name="brand" value="{{ old('brand') }}" class="form-control" placeholder="Contoh: ASUS"></div>
            <div class="asset-field"><label for="model">Model / Tipe</label><input id="model" name="model" value="{{ old('model') }}" class="form-control" placeholder="Contoh: X415"></div>
            <div class="asset-field"><label for="serial_number">Nomor Seri</label><input id="serial_number" name="serial_number" value="{{ old('serial_number') }}" class="form-control" placeholder="Nomor seri barang"></div>
        </div></section>
        <section class="asset-form-card"><div class="asset-section-heading"><span>02</span><div><h2>Penempatan</h2><p>Lokasi barang dan asal sumber pembiayaan.</p></div></div><div class="asset-form-grid"><div class="asset-field"><label for="location_id">Lokasi / Ruangan <b>*</b></label><select id="location_id" name="location_id" class="form-select @error('location_id') is-invalid @enderror"><option value="">Pilih lokasi</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected(old('location_id')==$location->id)>{{ $location->name }}</option>@endforeach</select>@error('location_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="asset-field"><label for="funding_source_id">Sumber Dana</label><select id="funding_source_id" name="funding_source_id" class="form-select"><option value="">Tidak ditentukan</option>@foreach($fundingSources as $source)<option value="{{ $source->id }}" @selected(old('funding_source_id')==$source->id)>{{ $source->code }} — {{ $source->name }}</option>@endforeach</select></div></div></section>
        <section class="asset-form-card"><div class="asset-section-heading"><span>03</span><div><h2>Pengadaan</h2><p>Informasi waktu, nilai, dan jumlah perolehan aset.</p></div></div><div class="asset-form-grid"><div class="asset-field"><label for="acquisition_year">Tahun Pengadaan <b>*</b></label><input type="number" id="acquisition_year" name="acquisition_year" value="{{ old('acquisition_year',date('Y')) }}" min="1900" max="{{ date('Y')+1 }}" class="form-control @error('acquisition_year') is-invalid @enderror">@error('acquisition_year')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="asset-field"><label for="acquisition_date">Tanggal Pengadaan</label><input type="date" id="acquisition_date" name="acquisition_date" value="{{ old('acquisition_date') }}" class="form-control"></div><div class="asset-field"><label for="acquisition_price">Harga Perolehan <b>*</b></label><div class="price-input"><span>Rp</span><input id="acquisition_price" name="acquisition_price" inputmode="numeric" value="{{ old('acquisition_price',0) }}" class="form-control @error('acquisition_price') is-invalid @enderror" placeholder="0"></div>@error('acquisition_price')<div class="asset-error">{{ $message }}</div>@enderror<small>Masukkan harga per satu barang.</small></div><div class="asset-field"><label for="quantity">Jumlah <b>*</b></label><input type="number" id="quantity" name="quantity" value="{{ old('quantity',1) }}" min="1" class="form-control @error('quantity') is-invalid @enderror">@error('quantity')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></section>
        <section class="asset-form-card"><div class="asset-section-heading"><span>04</span><div><h2>Kondisi & Dokumentasi</h2><p>Kondisi awal dan foto barang inventaris.</p></div></div><div class="asset-form-grid"><div class="asset-field"><label for="condition">Kondisi <b>*</b></label><select id="condition" name="condition" class="form-select"><option value="baik" @selected(old('condition','baik')==='baik')>Baik</option><option value="rusak_ringan" @selected(old('condition')==='rusak_ringan')>Rusak Ringan</option><option value="rusak_berat" @selected(old('condition')==='rusak_berat')>Rusak Berat</option></select></div><div class="asset-field span-2"><label>Foto Barang</label><div class="photo-upload"><div class="photo-preview" id="photoPreview"><i data-lucide="image-plus"></i><span>Belum ada foto</span></div><div><label for="photo" class="btn category-cancel-btn photo-select">Pilih Foto</label><input type="file" id="photo" name="photo" accept="image/jpeg,image/png,image/webp" hidden><p>JPG, PNG, atau WEBP. Maksimal 5 MB.</p>@error('photo')<div class="asset-error">{{ $message }}</div>@enderror</div></div></div><div class="asset-field span-2"><label for="description">Keterangan Tambahan</label><textarea id="description" name="description" rows="4" class="form-control" placeholder="Tambahkan informasi lain mengenai aset jika diperlukan.">{{ old('description') }}</textarea></div></div></section>
        <div class="asset-form-actions"><a href="{{ route('assets.index') }}" class="btn category-cancel-btn"><i data-lucide="arrow-left"></i>Batal</a><button type="submit" class="btn category-primary-btn asset-submit" id="assetSubmit"><span class="asset-submit-default"><i data-lucide="save"></i>Simpan Aset</span><span class="asset-submit-loading"><span class="auth-spinner"></span>Memproses...</span></button></div>
    </form>
</div>
@push('scripts')@vite('resources/js/asset-form.js')@endpush
</x-app-layout>
