<x-app-layout title="Detail Aset">
<div class="category-page asset-detail-page">
    <nav aria-label="breadcrumb"><ol class="breadcrumb category-breadcrumb"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li><li class="breadcrumb-item">Inventaris</li><li class="breadcrumb-item"><a href="{{ route('assets.index') }}">Data Aset</a></li><li class="breadcrumb-item active">Detail Aset</li></ol></nav>
    <header class="category-page-header asset-detail-header"><div><h1>{{ $asset->name }}</h1><p>{{ $asset->asset_code }}</p></div><div class="asset-detail-actions">@if(auth()->user()->isAdmin())<a href="{{ route('assets.edit',$asset) }}" class="btn category-primary-btn"><i data-lucide="pencil"></i>Edit Aset</a><a href="{{ route('asset-labels.single',$asset) }}" class="btn category-cancel-btn"><i data-lucide="printer"></i>Cetak Label</a>@endif</div></header>
    <div class="asset-detail-layout"><main>
        <section class="asset-detail-card asset-identity"><div class="asset-detail-photo">@if($asset->photo)<img src="{{ route('assets.photo', $asset) }}" alt="Foto {{ $asset->name }}">@else<i data-lucide="image"></i><span>Belum ada foto</span>@endif</div><div><div class="asset-detail-badges"><span class="asset-badge condition-{{ $asset->condition }}">{{ $asset->condition_label }}</span><span class="asset-badge status-{{ $asset->status }}">{{ $asset->status_label }}</span></div><h2>{{ $asset->name }}</h2><strong>{{ $asset->asset_code }}</strong><p>{{ $asset->description ?: 'Tidak ada keterangan tambahan.' }}</p></div></section>
        <section class="asset-detail-card"><div class="asset-detail-title"><i data-lucide="clipboard-list"></i><div><h2>Informasi Aset</h2><p>Identitas dan data pengadaan aset.</p></div></div><dl class="asset-info-grid">
            <div><dt>Kategori</dt><dd>{{ $asset->category->name }}</dd></div><div><dt>Merk</dt><dd>{{ $asset->brand ?: '—' }}</dd></div><div><dt>Model / Tipe</dt><dd>{{ $asset->model ?: '—' }}</dd></div><div><dt>Nomor Seri</dt><dd>{{ $asset->serial_number ?: '—' }}</dd></div><div><dt>Jumlah</dt><dd>{{ number_format($asset->quantity,0,',','.') }} barang</dd></div><div><dt>Lokasi / Ruangan</dt><dd>{{ $asset->location->name }}</dd></div><div><dt>Sumber Dana</dt><dd>{{ $asset->fundingSource?->name ?: '—' }}</dd></div><div><dt>Tahun Pengadaan</dt><dd>{{ $asset->acquisition_year }}</dd></div><div><dt>Tanggal Pengadaan</dt><dd>{{ $asset->acquisition_date?->locale('id')->translatedFormat('d F Y') ?: '—' }}</dd></div><div><dt>Harga per Unit</dt><dd>Rp {{ number_format((float)$asset->acquisition_price,0,',','.') }}</dd></div><div class="span-2"><dt>Total Nilai Aset</dt><dd class="asset-total-value">Rp {{ number_format((float)$asset->acquisition_price*$asset->quantity,0,',','.') }}</dd></div>
        </dl></section>
        <section class="asset-detail-card"><div class="asset-detail-title"><i data-lucide="history"></i><div><h2>Riwayat Aset</h2><p>Aktivitas yang berkaitan dengan aset ini.</p></div></div>@if($assetActivities->isEmpty())<div class="asset-history-empty"><i data-lucide="clock-3"></i><p>Belum ada riwayat aktivitas pada aset ini.</p></div>@else<div class="asset-mutation-history">@foreach($assetActivities as $activity)<a href="{{ $activity['url'] }}"><time>{{ $activity['date']->locale('id')->translatedFormat('d M Y') }}</time><span><i data-lucide="{{ $activity['icon'] }}"></i></span><div><strong>{{ $activity['title'] }}</strong><p>{{ $activity['description'] }}</p><small>{{ $activity['meta'] }}</small></div></a>@endforeach</div>@endif</section>
    </main><aside><section class="asset-detail-card asset-meta-card"><h2>Informasi Pencatatan</h2><dl><div><dt>Dibuat oleh</dt><dd>{{ $asset->creator?->name ?: 'Pengguna tidak tersedia' }}</dd></div><div><dt>Tanggal dibuat</dt><dd>{{ $asset->created_at->locale('id')->translatedFormat('d F Y, H:i') }}</dd></div><div><dt>Terakhir diperbarui</dt><dd>{{ $asset->updated_at->locale('id')->translatedFormat('d F Y, H:i') }}</dd></div></dl></section><a href="{{ route('assets.index') }}" class="asset-back-link"><i data-lucide="arrow-left"></i>Kembali ke Data Aset</a></aside></div>
</div>
</x-app-layout>
