<x-app-layout title="QR Code Aset">
@push('scripts')@vite('resources/js/asset-qr-codes.js')@endpush
<div class="category-page qr-page">
<nav><ol class="breadcrumb category-breadcrumb"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li><li class="breadcrumb-item">Inventaris</li><li class="breadcrumb-item active">QR Code Aset</li></ol></nav>
<header class="category-page-header"><div><h1>QR Code Aset</h1><p>Kelola dan unduh QR Code untuk identifikasi barang inventaris.</p></div></header>
<section class="category-mini-summary qr-summary"><div><span>Total Aset</span><strong>{{ number_format($summary['total'],0,',','.') }}</strong></div><i></i><div><span>QR Tersedia</span><strong>{{ number_format($summary['qr'],0,',','.') }}</strong></div><i></i><div><span>Aset Aktif</span><strong>{{ number_format($summary['active'],0,',','.') }}</strong></div></section>
<section class="category-panel qr-filter-panel"><form method="GET" class="asset-toolbar"><div class="category-search asset-search"><i data-lucide="search"></i><input name="search" value="{{ request('search') }}" placeholder="Cari kode atau nama aset..."></div><div class="asset-filters"><select name="category"><option value="">Semua Kategori</option>@foreach($categories as $item)<option value="{{ $item->id }}" @selected(request('category')==$item->id)>{{ $item->name }}</option>@endforeach</select><select name="location"><option value="">Semua Lokasi</option>@foreach($locations as $item)<option value="{{ $item->id }}" @selected(request('location')==$item->id)>{{ $item->name }}</option>@endforeach</select><select name="condition"><option value="">Semua Kondisi</option><option value="baik" @selected(request('condition')==='baik')>Baik</option><option value="rusak_ringan" @selected(request('condition')==='rusak_ringan')>Rusak Ringan</option><option value="rusak_berat" @selected(request('condition')==='rusak_berat')>Rusak Berat</option></select><select name="status"><option value="">Semua Status</option><option value="tersedia" @selected(request('status')==='tersedia')>Tersedia</option><option value="dipinjam" @selected(request('status')==='dipinjam')>Dipinjam</option><option value="perawatan" @selected(request('status')==='perawatan')>Perawatan</option><option value="dihapus" @selected(request('status')==='dihapus')>Dihapus</option></select></div><div class="asset-filter-actions"><button class="btn category-search-btn">Filter</button>@if(request()->hasAny(['search','category','location','condition','status']))<a href="{{ route('asset-qr-codes.index') }}" class="category-reset"><i data-lucide="rotate-ccw"></i>Reset</a>@endif</div></form></section>
@if($assets->isEmpty())<section class="category-panel category-empty"><div><i data-lucide="qr-code"></i></div><h2>QR Code aset tidak ditemukan</h2><p>Ubah pencarian atau filter untuk melihat QR Code aset lainnya.</p></section>@else
<form method="POST" action="{{ route('asset-qr-codes.print-selected') }}" target="_blank" id="qrSelectionForm">@csrf
<div class="qr-selection-toolbar" id="qrSelectionToolbar"><span><b id="qrSelectedCount">0</b> aset dipilih</span><button class="btn category-primary-btn" id="printSelectedQr" disabled><i data-lucide="printer"></i>Cetak QR Terpilih</button></div>
<section class="qr-card-grid">@foreach($assets as $asset)<article class="qr-card"><label class="qr-card-check" title="Pilih {{ $asset->name }}"><input type="checkbox" name="asset_ids[]" value="{{ $asset->id }}" class="qr-selector"><span></span></label><div class="qr-card-image"><img src="{{ $asset->qr_data_uri }}" alt="QR Code {{ $asset->asset_code }}"></div><div class="qr-card-body"><span class="qr-card-code">{{ $asset->asset_code }}</span><h2 title="{{ $asset->name }}">{{ $asset->name }}</h2><dl><div><dt>Kategori</dt><dd>{{ $asset->category->name }}</dd></div><div><dt>Lokasi</dt><dd>{{ $asset->location->name }}</dd></div></dl><div class="qr-card-status"><span>Status</span><b class="asset-badge status-{{ $asset->status }}">{{ $asset->status_label }}</b></div></div><footer><button type="button" class="qr-view-button" data-bs-toggle="modal" data-bs-target="#qrModal{{ $asset->id }}"><i data-lucide="eye"></i>Lihat QR</button><div class="dropdown"><button type="button" class="category-action" data-bs-toggle="dropdown" aria-label="Tindakan QR {{ $asset->asset_code }}"><i data-lucide="ellipsis-vertical"></i></button><ul class="dropdown-menu dropdown-menu-end category-action-menu"><li><a class="dropdown-item" data-turbo="false" href="{{ route('asset-qr-codes.download',$asset) }}"><i data-lucide="download"></i>Download PNG</a></li><li><a class="dropdown-item" target="_blank" href="{{ route('asset-qr-codes.print',$asset) }}"><i data-lucide="printer"></i>Print QR</a></li><li><a class="dropdown-item" href="{{ route('asset-labels.single',$asset) }}"><i data-lucide="qr-code"></i>Cetak Label Lengkap</a></li></ul></div></footer></article>
<div class="modal fade qr-preview-modal" id="qrModal{{ $asset->id }}" tabindex="-1" aria-labelledby="qrModalTitle{{ $asset->id }}" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><div><h2 id="qrModalTitle{{ $asset->id }}">Preview QR Code</h2><p>{{ $asset->asset_code }}</p></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Tutup"></button></div><div class="modal-body"><div class="qr-modal-school">@if($schoolSetting->logo_url)<img src="{{ $schoolSetting->logo_url }}" alt="Logo {{ $schoolSetting->display_name }}">@endif<strong>{{ $schoolSetting->display_name }}</strong></div><img class="qr-modal-image" src="{{ $asset->qr_data_uri }}" alt="QR Code besar {{ $asset->asset_code }}"><h3>{{ $asset->name }}</h3><b>{{ $asset->asset_code }}</b><p><span>Lokasi</span>{{ $asset->location->name }}</p><small>Scan untuk melihat informasi aset</small></div><div class="modal-footer"><button type="button" class="btn category-cancel-btn" data-bs-dismiss="modal">Tutup</button><a class="btn category-cancel-btn" data-turbo="false" href="{{ route('asset-qr-codes.download',$asset) }}"><i data-lucide="download"></i>Download QR</a><a class="btn category-primary-btn" target="_blank" href="{{ route('asset-qr-codes.print',$asset) }}"><i data-lucide="printer"></i>Print QR</a></div></div></div></div>
@endforeach</section></form><div class="category-pagination"><span>Menampilkan {{ $assets->firstItem() }}–{{ $assets->lastItem() }} dari {{ $assets->total() }} aset</span>{{ $assets->links() }}</div>@endif
</div></x-app-layout>
