<x-app-layout title="Notifikasi">@push('scripts')@vite('resources/css/notifications.css')@endpush<div class="category-page notification-page"><nav><ol class="breadcrumb category-breadcrumb"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li><li class="breadcrumb-item active">Notifikasi</li></ol></nav><header class="category-page-header"><div><h1>Notifikasi</h1><p>Informasi dan aktivitas penting yang membutuhkan perhatian.</p></div>@if(auth()->user()->unreadNotifications()->exists())<form method="POST" action="{{ route('notifications.read-all') }}">@csrf @method('PATCH')<button class="btn category-cancel-btn"><i data-lucide="circle-check"></i>Tandai Semua Dibaca</button></form>@endif</header><section class="category-panel"><form method="GET" class="notification-filters"><select name="status"><option value="">Semua Status</option><option value="unread" @selected(request('status')==='unread')>Belum Dibaca</option><option value="read" @selected(request('status')==='read')>Sudah Dibaca</option></select><select name="type"><option value="">Semua Jenis</option><option value="loan" @selected(request('type')==='loan')>Peminjaman</option><option value="maintenance" @selected(request('type')==='maintenance')>Perawatan</option><option value="disposal" @selected(request('type')==='disposal')>Penghapusan</option><option value="mutation" @selected(request('type')==='mutation')>Mutasi</option><option value="system" @selected(request('type')==='system')>Sistem</option></select><button class="btn category-search-btn">Filter</button></form><div class="notification-list">@forelse($notifications as $notification)<article class="notification-row {{ $notification->read_at?'':'unread' }}"><a class="notification-main" href="{{ route('notifications.open',$notification->id) }}"><span class="notification-item-icon"><i data-lucide="{{ $notification->data['icon'] ?? 'info' }}"></i></span><span><b>{{ $notification->data['title'] ?? 'Notifikasi' }}</b><small>{{ $notification->data['message'] ?? '' }}</small><time>{{ $notification->created_at->locale('id')->translatedFormat('d M Y, H:i') }} · {{ $notification->created_at->locale('id')->diffForHumans() }}</time></span></a><div class="notification-actions">@if(!$notification->read_at)<form method="POST" action="{{ route('notifications.read',$notification->id) }}">@csrf @method('PATCH')<button title="Tandai dibaca"><i data-lucide="circle-check"></i></button></form>@endif<form method="POST" action="{{ route('notifications.destroy',$notification->id) }}">@csrf @method('DELETE')<button title="Hapus"><i data-lucide="trash-2"></i></button></form></div></article>@empty<div class="notification-empty"><i data-lucide="bell"></i><b>Tidak ada notifikasi</b><span>Semua informasi penting akan muncul di sini.</span></div>@endforelse</div>@if($notifications->hasPages())<div class="category-pagination">
    <div class="pagination-wrapper">
        <span>Tampilkan:</span>
        <select class="per-page-select" onchange="const url = new URL(window.location.href); url.searchParams.set('per_page', this.value); url.searchParams.set('page', 1); window.location.href = url.toString();">
            <option value="10" @selected(request('per_page', 10) == 10)>10</option>
            <option value="20" @selected(request('per_page') == 20)>20</option>
            <option value="50" @selected(request('per_page') == 50)>50</option>
            <option value="100" @selected(request('per_page') == 100)>100</option>
        </select>
        <span>Menampilkan {{ $notifications->firstItem() }}–{{ $notifications->lastItem() }} dari {{ $notifications->total() }} notifikasi</span>
    </div>
    {{ $notifications->links() }}
</div>@endif
</section></div></x-app-layout>
