<?php
namespace App\Http\Controllers;
use App\Http\Requests\RejectAssetDisposalRequest;use App\Http\Requests\StoreAssetDisposalRequest;use App\Models\Asset;use App\Models\AssetDisposal;use App\Models\AssetMaintenance;use App\Services\AssetDisposalService;use App\Services\AssetNotificationService;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;use Illuminate\View\View;use Symfony\Component\HttpFoundation\StreamedResponse;use Throwable;
class AssetDisposalController extends Controller{
public function index(Request $request):View{$f=$request->validate(['search'=>['nullable','string','max:100'],'status'=>['nullable','in:diajukan,disetujui,ditolak'],'method'=>['nullable','in:pemusnahan,penjualan,hibah,hilang,lainnya'],'date'=>['nullable','date'],'condition'=>['nullable','in:baik,rusak_ringan,rusak_berat'],'per_page'=>['nullable','integer','in:10,20,50,100']]);$perPage=$request->integer('per_page',10);$disposals=AssetDisposal::with('asset.location:id,name')->when($f['search']??null,fn($q,$s)=>$q->whereHas('asset',fn($a)=>$a->where('asset_code','like',"%{$s}%")->orWhere('name','like',"%{$s}%")))->when($f['status']??null,fn($q,$v)=>$q->where('status',$v))->when($f['method']??null,fn($q,$v)=>$q->where('disposal_method',$v))->when($f['date']??null,fn($q,$v)=>$q->whereDate('disposal_date',$v))->when($f['condition']??null,fn($q,$v)=>$q->where('condition_at_disposal',$v))->latest('disposal_date')->latest('id')->paginate($perPage)->withQueryString();$assets=Asset::with('location:id,name')->whereNotIn('status',['dipinjam','perawatan','dihapus'])->whereDoesntHave('loans',fn($q)=>$q->whereNull('returned_at'))->whereDoesntHave('maintenances',fn($q)=>$q->whereIn('maintenance_status',AssetMaintenance::ACTIVE_STATUSES))->whereDoesntHave('disposals',fn($q)=>$q->where('status','diajukan'))->orderBy('name')->get();return view('asset-disposals.index',['disposals'=>$disposals,'assets'=>$assets,'pendingCount'=>AssetDisposal::where('status','diajukan')->count(),'approvedCount'=>AssetDisposal::where('status','disetujui')->count(),'rejectedCount'=>AssetDisposal::where('status','ditolak')->count(),'deletedAssets'=>Asset::where('status','dihapus')->count()]);}
public function store(StoreAssetDisposalRequest $request,AssetDisposalService $service,AssetNotificationService $notifications):RedirectResponse{$data=$request->validated();$file=$request->file('document_file')?->store('asset-disposals','public');unset($data['document_file']);if($file)$data['document_file']=$file;try{$disposal=$service->create($data,$request->user());}catch(Throwable $e){if($file)Storage::disk('public')->delete($file);throw $e;}$disposal->load('asset');$notifications->heads('Menunggu Persetujuan','Penghapusan '.$disposal->asset->name.' menunggu persetujuan Anda.','disposal_pending',route('asset-disposals.show',$disposal),'disposal',$disposal->id,'disposal_pending:'.$disposal->id);return redirect()->route('asset-disposals.show',$disposal)->with('success','Pengajuan penghapusan berhasil dibuat.');}
public function show(AssetDisposal $disposal):View{return view('asset-disposals.show',['disposal'=>$disposal->load(['asset.location','creator','approver'])]);}
public function approve(Request $request,AssetDisposal $disposal,AssetDisposalService $service,AssetNotificationService $notifications):RedirectResponse{$service->approve($disposal,$request->user());$disposal->load('asset');$notifications->admins('Penghapusan Disetujui','Penghapusan '.$disposal->asset->name.' telah disetujui.','disposal_approved',route('asset-disposals.show',$disposal),'disposal',$disposal->id,'disposal_approved:'.$disposal->id);return redirect()->route('asset-disposals.show',$disposal)->with('success','Penghapusan aset berhasil disetujui.');}
public function reject(RejectAssetDisposalRequest $request,AssetDisposal $disposal,AssetDisposalService $service,AssetNotificationService $notifications):RedirectResponse{$service->reject($disposal,$request->validated(),$request->user());$disposal->load('asset');$notifications->admins('Penghapusan Ditolak','Pengajuan penghapusan '.$disposal->asset->name.' ditolak.','disposal_rejected',route('asset-disposals.show',$disposal),'disposal',$disposal->id,'disposal_rejected:'.$disposal->id);return redirect()->route('asset-disposals.show',$disposal)->with('success','Pengajuan penghapusan ditolak.');}
public function document(AssetDisposal $disposal):StreamedResponse{abort_unless($disposal->document_file&&Storage::disk('public')->exists($disposal->document_file),404);return Storage::disk('public')->download($disposal->document_file);}}
