<x-app-layout title="Preview Label Inventaris">
<div class="label-preview-page">
    <nav aria-label="breadcrumb" class="print-hidden"><ol class="breadcrumb category-breadcrumb"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route('asset-labels.index') }}">Cetak Label</a></li><li class="breadcrumb-item active">Preview</li></ol></nav>
    <header class="category-page-header label-preview-header print-hidden"><div><h1>Preview {{ $labels->count() }} Label</h1><p>Periksa label sebelum mencetak pada kertas A4.</p></div><div><a href="{{ route('asset-labels.index') }}" class="btn category-cancel-btn"><i data-lucide="arrow-left"></i>Kembali</a><button type="button" class="btn category-primary-btn" onclick="window.print()"><i data-lucide="printer"></i>Print</button></div></header>
    <section class="label-preview-tools print-hidden"><div><strong>Ukuran Label</strong><span>{{ ['small'=>'Kecil · 70 × 35 mm','medium'=>'Sedang · 90 × 50 mm','large'=>'Besar · 100 × 60 mm'][$size] }}</span></div>@if($singleAsset && $singleAsset->quantity > 1)<form method="GET" action="{{ route('asset-labels.single',$singleAsset) }}" class="single-label-quantity"><input type="hidden" name="size" value="{{ $size }}"><label for="previewQuantity">Jumlah label</label><input id="previewQuantity" type="number" name="quantity" value="{{ $labels->count() }}" min="1" max="{{ $singleAsset->quantity }}"><span>dari {{ $singleAsset->quantity }} unit</span><button class="btn category-cancel-btn">Terapkan</button></form>@endif<div class="label-size-switch"><a href="{{ $singleAsset ? route('asset-labels.single',[$singleAsset,'size'=>'small','quantity'=>$labels->count()]) : '#' }}" data-preview-size="small" class="{{ $size==='small'?'active':'' }}">Kecil</a><a href="{{ $singleAsset ? route('asset-labels.single',[$singleAsset,'size'=>'medium','quantity'=>$labels->count()]) : '#' }}" data-preview-size="medium" class="{{ $size==='medium'?'active':'' }}">Sedang</a><a href="{{ $singleAsset ? route('asset-labels.single',[$singleAsset,'size'=>'large','quantity'=>$labels->count()]) : '#' }}" data-preview-size="large" class="{{ $size==='large'?'active':'' }}">Besar</a></div></section>
    <div class="label-paper-wrap"><section class="label-paper label-size-{{ $size }}" id="labelPaper">@foreach($labels as $label)@include('asset-labels.partials.label',$label)@endforeach</section></div>
</div>
@push('scripts')<script>document.querySelectorAll('[data-preview-size]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();const size=link.dataset.previewSize;const paper=document.getElementById('labelPaper');paper.className='label-paper label-size-'+size;document.querySelectorAll('[data-preview-size]').forEach(item=>item.classList.toggle('active',item===link));}));</script>@endpush
</x-app-layout>
